-- Name: global_settings; Type: TABLE; Schema: public; Owner: deploy
--
CREATE TABLE public.global_settings (
    id integer NOT NULL,
    default_logo character varying(255),
    company_name character varying(255),
    base_request_number integer,
    bladelogic_enabled boolean,
    bladelogic_ip_address character varying(255),
    bladelogic_username character varying(255),
    bladelogic_password character varying(255),
    bladelogic_rolename character varying(255),
    bladelogic_profile character varying(255),
    capistrano_enabled boolean,
    hudson_enabled boolean,
    session_key character varying(255),
    timezone character varying(255),
    one_click_completion boolean,
    authentication_mode integer,
    default_date_format character varying(255),
    forgot_password boolean,
    ldap_host character varying(255),
    ldap_port character varying(255),
    ldap_component character varying(255),
    cas_server character varying(255),
    base_url character varying(255),
    calendar_preferences character varying(1000),
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    limit_versions boolean,
    automation_enabled boolean DEFAULT false,
    commit_on_completion boolean DEFAULT true,
    ldap_bind_user character varying(255),
    ldap_bind_password character varying(255),
    ldap_bind_base character varying(255),
    ldap_account_attribute character varying(255),
    ldap_auth_type integer DEFAULT 0 NOT NULL,
    ldap_first_name_attribute character varying(255),
    ldap_last_name_attribute character varying(255),
    ldap_mail_attribute character varying(255),
    session_timeout integer,
    messaging_enabled boolean DEFAULT false,
    ldap_group_search_base character varying(255),
    default_step_estimate integer DEFAULT 5,
    allow_alternate_servers boolean DEFAULT false,
    ldap_type character varying(255) DEFAULT 'ldap'::character varying NOT NULL
);
ALTER TABLE public.global_settings OWNER TO deploy;
--
