-- Name: requests; Type: TABLE; Schema: public; Owner: deploy
--
CREATE TABLE public.requests (
    id integer NOT NULL,
    business_process_id integer,
    app_id integer,
    environment_id integer DEFAULT 0,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    scheduled_at timestamp without time zone,
    target_completion_at timestamp without time zone,
    notify_on_request_start boolean DEFAULT false NOT NULL,
    deployment_coordinator_id integer,
    release_id integer,
    aasm_state character varying(255),
    completed_at timestamp without time zone,
    started_at timestamp without time zone,
    frozen_app bytea,
    frozen_environment bytea,
    frozen_business_process bytea,
    frozen_deployment_coordinator bytea,
    frozen_release bytea,
    category_id integer,
    request_template_id integer,
    notify_on_request_complete boolean DEFAULT false NOT NULL,
    notify_on_step_complete boolean DEFAULT false NOT NULL,
    notify_on_step_start boolean DEFAULT false NOT NULL,
    additional_email_addresses character varying(255),
    planned_at timestamp without time zone,
    deleted_at timestamp without time zone,
    notify_on_request_hold boolean DEFAULT false NOT NULL,
    notify_on_step_block boolean DEFAULT false NOT NULL,
    name character varying(255),
    description text,
    requestor_id integer,
    frozen_requestor bytea,
    activity_id integer,
    auto_start boolean DEFAULT false NOT NULL,
    wiki_url text,
    plan_member_id integer,
    server_association_id integer,
    server_association_type character varying(255),
    owner_id integer,
    rescheduled boolean,
    promotion boolean DEFAULT false,
    cancelled_at timestamp without time zone,
    created_from_template boolean DEFAULT false,
    notify_on_step_problem boolean,
    notify_on_step_ready boolean,
    notify_on_request_cancel boolean,
    notify_on_request_planned boolean DEFAULT false NOT NULL,
    notify_on_request_problem boolean DEFAULT false NOT NULL,
    notify_on_request_resolved boolean DEFAULT false,
    notify_on_request_step_owners boolean DEFAULT false NOT NULL,
    notify_on_step_step_owners boolean DEFAULT false NOT NULL,
    notify_on_step_requestor_owner boolean DEFAULT false NOT NULL,
    notify_on_step_participiant boolean DEFAULT false NOT NULL,
    notify_on_request_participiant boolean DEFAULT false NOT NULL,
    notify_group_only boolean DEFAULT true NOT NULL,
    origin_request_template_id integer,
    estimate integer,
    deployment_window_event_id integer,
    notify_on_dw_fail boolean DEFAULT false NOT NULL,
    automatically_start_errors text,
    parent_request_id integer,
    notify_on_step_not_started boolean DEFAULT false,
    run_by_id integer
);
ALTER TABLE public.requests OWNER TO deploy;
--
