-- Name: users; Type: TABLE; Schema: public; Owner: deploy
--
CREATE TABLE public.users (
    id integer NOT NULL,
    login character varying(255),
    email character varying(255) DEFAULT ''::character varying,
    first_name character varying(255),
    last_name character varying(255),
    encrypted_password character varying(128) DEFAULT ''::character varying,
    password_salt character varying(255) DEFAULT ''::character varying,
    remember_token character varying(255),
    remember_token_expires_at timestamp without time zone,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    admin boolean DEFAULT false,
    active boolean DEFAULT true NOT NULL,
    old_roles text,
    employment_type character varying(255) DEFAULT 'permanent'::character varying NOT NULL,
    location character varying(255),
    max_allocation integer DEFAULT 100 NOT NULL,
    system_user boolean DEFAULT true NOT NULL,
    type character varying(255),
    root boolean DEFAULT false NOT NULL,
    time_zone character varying(255),
    list_order character varying(255) DEFAULT 'desc'::character varying,
    first_time_login boolean DEFAULT true,
    is_reset_password boolean DEFAULT false,
    calendar_preferences text,
    last_response_at timestamp without time zone,
    global_access boolean DEFAULT false,
    first_day_on_calendar integer DEFAULT 0,
    remember_created_at timestamp without time zone,
    contact_number character varying(255),
    api_key character varying(255),
    reset_password_token character varying(255),
    reset_password_sent_at timestamp without time zone,
    sign_in_count integer DEFAULT 0,
    current_sign_in_at timestamp without time zone,
    last_sign_in_at timestamp without time zone,
    current_sign_in_ip character varying(255),
    last_sign_in_ip character varying(255)
);
ALTER TABLE public.users OWNER TO deploy;
--
