CREATE TABLE "HR"."REGIONS" 
   (	"REGION_ID" NUMBER, 
	"REGION_NAME" VARCHAR2(25), 
	"COLUMN1" VARCHAR2(20) DEFAULT NULL, 
	"COLUMN2" VARCHAR2(20) DEFAULT NULL, 
	"COLUMN3" VARCHAR2(20) DEFAULT NULL
   ) ;
  
  ALTER TABLE "HR"."REGIONS" MODIFY ("REGION_ID" CONSTRAINT "REGION_ID_NN" NOT NULL ENABLE);
  ALTER TABLE "HR"."REGIONS" ADD CONSTRAINT "REG_ID_PK" PRIMARY KEY ("REGION_ID")
  USING INDEX  ENABLE; 