CREATE TABLE "MP_DEV"."TMP_SQL" 
   (	"LOOP_NO" NUMBER(10,0), 
	"SID" NUMBER, 
	"SERIAL#" NUMBER, 
	"PROCESS" VARCHAR2(24), 
	"PROGRAM" VARCHAR2(48), 
	"MODULE" VARCHAR2(64), 
	"OSUSER" VARCHAR2(30), 
	"SCHEMANAME" VARCHAR2(30), 
	"ACTION" VARCHAR2(64), 
	"MACHINE" VARCHAR2(64), 
	"PORT" NUMBER, 
	"TERMINAL" VARCHAR2(30), 
	"ADDRESS" RAW(8), 
	"PIECE" NUMBER, 
	"SQL_TEXT" VARCHAR2(64)
   ) ;

   